app = "bonker-api"
primary_region = "iad"

[build]
  builder = "heroku"
  buildpacks = ["heroku/nodejs"]

[env]
  NODE_ENV = "production"
  PORT = "3001"

[[services]]
  internal_port = 3001
  processes = ["app"]
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source = "bonker_data"
  destination = "/app/tester/server/data"
  initial_size = 10
